# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/router/Documents/muduo_example/timing wheel"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/router/Documents/muduo_example/timing wheel"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/router/Documents/muduo_example/timing wheel/CMakeFiles" "/home/router/Documents/muduo_example/timing wheel/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/router/Documents/muduo_example/timing wheel/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named echo

# Build rule for target.
echo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 echo
.PHONY : echo

# fast build rule for target.
echo/fast:
	$(MAKE) -f CMakeFiles/echo.dir/build.make CMakeFiles/echo.dir/build
.PHONY : echo/fast

#=============================================================================
# Target rules for targets named bucket_echo

# Build rule for target.
bucket_echo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bucket_echo
.PHONY : bucket_echo

# fast build rule for target.
bucket_echo/fast:
	$(MAKE) -f CMakeFiles/bucket_echo.dir/build.make CMakeFiles/bucket_echo.dir/build
.PHONY : bucket_echo/fast

#=============================================================================
# Target rules for targets named iopool_echo

# Build rule for target.
iopool_echo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 iopool_echo
.PHONY : iopool_echo

# fast build rule for target.
iopool_echo/fast:
	$(MAKE) -f CMakeFiles/iopool_echo.dir/build.make CMakeFiles/iopool_echo.dir/build
.PHONY : iopool_echo/fast

bucket_echo.o: bucket_echo.cc.o

.PHONY : bucket_echo.o

# target to build an object file
bucket_echo.cc.o:
	$(MAKE) -f CMakeFiles/bucket_echo.dir/build.make CMakeFiles/bucket_echo.dir/bucket_echo.cc.o
.PHONY : bucket_echo.cc.o

bucket_echo.i: bucket_echo.cc.i

.PHONY : bucket_echo.i

# target to preprocess a source file
bucket_echo.cc.i:
	$(MAKE) -f CMakeFiles/bucket_echo.dir/build.make CMakeFiles/bucket_echo.dir/bucket_echo.cc.i
.PHONY : bucket_echo.cc.i

bucket_echo.s: bucket_echo.cc.s

.PHONY : bucket_echo.s

# target to generate assembly for a file
bucket_echo.cc.s:
	$(MAKE) -f CMakeFiles/bucket_echo.dir/build.make CMakeFiles/bucket_echo.dir/bucket_echo.cc.s
.PHONY : bucket_echo.cc.s

circuit_buffer.o: circuit_buffer.cc.o

.PHONY : circuit_buffer.o

# target to build an object file
circuit_buffer.cc.o:
	$(MAKE) -f CMakeFiles/bucket_echo.dir/build.make CMakeFiles/bucket_echo.dir/circuit_buffer.cc.o
.PHONY : circuit_buffer.cc.o

circuit_buffer.i: circuit_buffer.cc.i

.PHONY : circuit_buffer.i

# target to preprocess a source file
circuit_buffer.cc.i:
	$(MAKE) -f CMakeFiles/bucket_echo.dir/build.make CMakeFiles/bucket_echo.dir/circuit_buffer.cc.i
.PHONY : circuit_buffer.cc.i

circuit_buffer.s: circuit_buffer.cc.s

.PHONY : circuit_buffer.s

# target to generate assembly for a file
circuit_buffer.cc.s:
	$(MAKE) -f CMakeFiles/bucket_echo.dir/build.make CMakeFiles/bucket_echo.dir/circuit_buffer.cc.s
.PHONY : circuit_buffer.cc.s

echo.o: echo.cc.o

.PHONY : echo.o

# target to build an object file
echo.cc.o:
	$(MAKE) -f CMakeFiles/echo.dir/build.make CMakeFiles/echo.dir/echo.cc.o
.PHONY : echo.cc.o

echo.i: echo.cc.i

.PHONY : echo.i

# target to preprocess a source file
echo.cc.i:
	$(MAKE) -f CMakeFiles/echo.dir/build.make CMakeFiles/echo.dir/echo.cc.i
.PHONY : echo.cc.i

echo.s: echo.cc.s

.PHONY : echo.s

# target to generate assembly for a file
echo.cc.s:
	$(MAKE) -f CMakeFiles/echo.dir/build.make CMakeFiles/echo.dir/echo.cc.s
.PHONY : echo.cc.s

iopool_echo.o: iopool_echo.cc.o

.PHONY : iopool_echo.o

# target to build an object file
iopool_echo.cc.o:
	$(MAKE) -f CMakeFiles/iopool_echo.dir/build.make CMakeFiles/iopool_echo.dir/iopool_echo.cc.o
.PHONY : iopool_echo.cc.o

iopool_echo.i: iopool_echo.cc.i

.PHONY : iopool_echo.i

# target to preprocess a source file
iopool_echo.cc.i:
	$(MAKE) -f CMakeFiles/iopool_echo.dir/build.make CMakeFiles/iopool_echo.dir/iopool_echo.cc.i
.PHONY : iopool_echo.cc.i

iopool_echo.s: iopool_echo.cc.s

.PHONY : iopool_echo.s

# target to generate assembly for a file
iopool_echo.cc.s:
	$(MAKE) -f CMakeFiles/iopool_echo.dir/build.make CMakeFiles/iopool_echo.dir/iopool_echo.cc.s
.PHONY : iopool_echo.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... echo"
	@echo "... bucket_echo"
	@echo "... iopool_echo"
	@echo "... rebuild_cache"
	@echo "... bucket_echo.o"
	@echo "... bucket_echo.i"
	@echo "... bucket_echo.s"
	@echo "... circuit_buffer.o"
	@echo "... circuit_buffer.i"
	@echo "... circuit_buffer.s"
	@echo "... echo.o"
	@echo "... echo.i"
	@echo "... echo.s"
	@echo "... iopool_echo.o"
	@echo "... iopool_echo.i"
	@echo "... iopool_echo.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

